
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev}
      POSTGRES_DB: ${DB_NAME:-auth}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  auth_app:
    build:
      context: .
      dockerfile: dockerfile.dev
    env_file:
      - .env.prod
      - .env.dev # second because it overrides the first
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

